"""Add Thread, Subreddit columns

Revision ID: 4ef73cd95ed2
Revises: 
Create Date: 2015-03-11 10:20:38.875321

"""

# revision identifiers, used by Alembic.
revision = '4ef73cd95ed2'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('threads')
    op.drop_table('subreddits')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subreddits',
    sa.Column('name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('description', sa.VARCHAR(length=2500), nullable=True),
    sa.Column('admin_id', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('pk', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], [u'users.pk'], ),
    sa.PrimaryKeyConstraint('pk')
    )
    op.create_table('threads',
    sa.Column('title', sa.VARCHAR(length=100), nullable=True),
    sa.Column('text', sa.VARCHAR(length=2000), nullable=True),
    sa.Column('link', sa.VARCHAR(length=1000), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('subreddit_id', sa.INTEGER(), nullable=True),
    sa.Column('votes', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('pk', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['subreddit_id'], [u'subreddits.pk'], ),
    sa.ForeignKeyConstraint(['user_id'], [u'users.pk'], ),
    sa.PrimaryKeyConstraint('pk')
    )
    op.create_table('users',
    sa.Column('username', sa.VARCHAR(length=100), nullable=True),
    sa.Column('password', sa.VARCHAR(length=200), nullable=True),
    sa.Column('email', sa.VARCHAR(length=200), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('pk', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('pk')
    )
    ### end Alembic commands ###
